start_program:
  target:
    device:
      - integration: home_connect
  fields:
    program:
      example: "Dishcare.Dishwasher.Program.Auto2"
      required: true
      selector:
        text:
    key:
      example: "BSH.Common.Option.StartInRelative"
      selector:
        text:
    value:
      example: 1800
      selector:
        object:
    unit:
      example: "seconds"
      selector:
        text:
select_program:
  target:
    device:
      - integration: home_connect
  fields:
    program:
      example: "Dishcare.Dishwasher.Program.Auto2"
      required: true
      selector:
        text:
    key:
      example: "BSH.Common.Option.StartInRelative"
      selector:
        text:
    value:
      example: 1800
      selector:
        object:
    unit:
      example: "seconds"
      selector:
        text:
pause_program:
  target:
    device:
      - integration: home_connect
resume_program:
  target:
    device:
      - integration: home_connect
set_option_active:
  target:
    device:
      - integration: home_connect
  fields:
    key:
      example: "LaundryCare.Dryer.Option.DryingTarget"
      required: true
      selector:
        text:
    value:
      example: "LaundryCare.Dryer.EnumType.DryingTarget.IronDry"
      required: true
      selector:
        object:
set_option_selected:
  target:
    device:
      - integration: home_connect
  fields:
    key:
      example: "LaundryCare.Dryer.Option.DryingTarget"
      required: true
      selector:
        text:
    value:
      example: "LaundryCare.Dryer.EnumType.DryingTarget.IronDry"
      required: true
      selector:
        object:
change_setting:
  target:
    device:
      - integration: home_connect
  fields:
    key:
      example: "BSH.Common.Setting.ChildLock"
      required: true
      selector:
        text:
    value:
      example: "true"
      required: true
      selector:
        object:
