# Describes the format for available image services

snapshot:
  target:
    entity:
      domain: image
  fields:
    filename:
      required: true
      example: "/tmp/snapshot_{{ entity_id.name }}.jpg"
      selector:
        text:
